modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
[[mods]]
modId="recipe_fixer"
version="0.7"
displayName="Recipe Fixer"
logoFile=""
credits="by lu3arm"
authors="lu3arm"
description='''
More recipes for Minecraft
'''
[[dependencies.recipe_fixer]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.recipe_fixer]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17,1.20)"
    ordering="NONE"
    side="BOTH"
